# Generated by Django 2.1 on 2018-09-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_taskinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='tasktipflg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
