# Generated by Django 2.1 on 2018-09-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_taskinfo_tasktipflg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='tasktipflg',
            field=models.IntegerField(default=0),
        ),
    ]
